spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/shannon.chen/spring-cloud-config
          search-paths: SC-BOOK-CONFIG
          repos:
            simple: https://gitee.com/shannon.chen/simple
            uri: https://gitee.com/shannon.chen/spring-cloud-config-special
          local:
            pattern: local*
            uri: /Users/shannon/all_test/spring-cloud-config
  application:
    name: ch12-2-config-server-placeholders
server:
  port: 9090
logging:
  level:
    root: debug
