spring:
  profiles:
    active: standalone
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

eureka:
  server:
    use-read-only-response-cache: false
management:
  endpoints:
    web:
      exposure:
        include: '*'